```{r include=FALSE, cache=FALSE}
rm(list = ls(all = TRUE))
```
# Introduction

Understanding how and why trees respond to drought is critical to predicting forest drought responses and climate change feedbacks.

Forests are diverse in terms of tree sizes and functional traits, and it is known that trees varying in size and functional traits respond differently to drought (e.g., [@bennett_larger_2015]; REFS). Therefore, in order to understand whole-forest response to drought, we need to know how responses vary by tree size/ species. To do so, there are four fundamental questions that must be addressed:

*First, how significant is the effect of individual drought years?*
Droughts are rarely explicitly defined in ecological studies [@slette_how_2019], yet no two droughts are the same. This study addressed this by analyzing trees' resistance to drought within and across three defined drought periods.

*Second, what drives the observed tendency for large trees to suffer more during drought?*  
[@bennett_larger_2015] showed that in forests globally, large trees suffer greater growth reductions during drought. However, this analysis quantified tree size based on DBH, which has no direct mechanistic meaning. This study proposed three major mechanisms (besides insects): (1) inherently greater biophysical challenge of being tall; (2) greater exposure of the crowns of large trees; and (3) greater water availability. It is also expected that roots play a role, though these hypotheses still need to be tested.

*Third, how do species' traits influence drought response?* 
Analyzing drought responses on the species level does not fully explain mechanisms and is not feasible in diverse forests. The solution is a trait-based approach. Leaf hydraulic traits hold more promise than more commonly/traditionally-measured traits such as wood density and SLA (Medeiros et al.). 

*Fourth, how do tree size and functional traits interact to influence drought response?*
It is possible that the pattern observed by [@bennett_larger_2015] could be caused by smaller trees being more drought resistant. Alternatively, larger trees may have more drought-resistant traits as adpatations to greater biophysical challenges.



*Hypotheses*

**1. How significant are individual drought years on a long time-frame trend?**
1.1 Individual drought scenario is a strong predictor of drought stress.

    * P1.1 - Drought stress is proportional to the severity of each drought.

**2. Why do larger trees suffer greater growth declines during drought?**
Our forest displays the same trend as most forests globally [@bennett_larger_2015]. (Note that Bennett et al. 2015 identified only one study on tree growth responses to drought in the Eastern US temperate deciduous biome. We know little about how tree size shapes drought response in this biome.)

2.1 DBH is a strong predictor of drought stress.

    * P2.2-Drought response increases with DBH at time of drought.

2.2. Height is a strong predictor of drought stress.

    * P2.2-Drought response increases with height at time of drought.
    * P2.2a - Drought response is better predicted by height than DBH.

2.3. Large trees suffer more during drought because of greater exposure (to radiation, wind, etc.)--either in relation to neighboring trees or because of position on landscape.

    * P3.1- Trees currently in a dominant canopy position suffered more during drought. 
    
2.4. Rooting volume/depth relative to water sources are critical in drought response. Effects of drought on larger trees are mediated by the fact that large trees have better access to water.
  
     * P3.2- drought response increases with topographic wetness index

**3. Do species functional traits predict drought response?**

     * P3.1 - diffuse porous species are more sensitive than ring porous (previously observed in eastern dec forests- Elliot et al. 2015, Friedrichs et al. 2009)
     * P3.2 - higher percent leaf area predicts higher drought stress
     * P3.3 - higher leaf mass area correlates positively to drought resistance (more sclerophyllous vegetation [thick leaves] usually means more adaptation) [Abrams 1990] [Guerfel et al 2009]
     * P3.4 - TLP correlates negatively with drought resistance (NEVER tested),
     * P3.5 - higher wood density means more drought resistant

**4. How are functional traits distributed across size classes, and how does this affect size-resistance relationship?** 

4.1. Larger/ more exposed trees have more drought resistant traits, meaning size effects are buffered by traits  
4.1_alt. Larger trees suffer more because they have more drought vulnerable traits.

     * P3.1a- TLP is lower (larger negative) in taller/canopy trees
     * P3.1b- diffuse porous species more common in understory 
   
     * P3.2- Inclusion of TLP / rp in model does not eliminate or significantly reduce effect of tree size.


**I think for #4 here the focus should be on hypotheses looking at the overall trend compared to the specific scenarios?**

**4. How do droughts vary in their affect on tree resistance? **

    * P4.1 - The combined-years scenario will have more explaining variables than the individual scenarios.
    * P4.2 - Inclusion of leaf hydraulic traits does not eliminate or significantly reduce effect of tree size.
    * P4.3 - Drought resistance for each scenario will be explained more by hydraulic traits than by the biophysical environment