---
title: "Response to reviews"
output: pdf_document

bibliography: ["book.bib",  "packages.bib"]
link-citations: yes
biblio-style: "apalike"
csl: new-phytologist.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Dear Editor:

We have revised our manuscript, “Tree height and leaf drought tolerance traits shape growth responses across droughts in a temperate broadleaf forest”, according to the recommendations of reviewers. These changes have further strengthened the manuscript. 

A complete list of substantive changes is as follows:

* Most importantly, we have added analyses parallel to those for resistance for both recovery and resilience. Because we feel that resilience is the more interesting and informative of these two, we have given it precedence for inclusion in main manuscript figures, where space is limiting. Specifically, we have added a density plot of resilience to Fig.1 (+ parallel plot for recovery in the SI), a plot of resilience by species to Fig. 3 (+ parallel plot for recovery in the SI), and plots of the best models for both recovery and resilience to Fig. 4. We have also added recovery and resilience to the hypothesis table (Table 1), and their definitions to Table 3. We have also modified the text throughout and included relevant tables presenting statistics in the supplementary info.

* To account for the fact that we now consider three main response variables, and in response to a comment from R3, we slightly modified the criteria for inclusion of traits in the main statistical models. As now stated in the methods, "Trait variables were considered appropriate for inclusion in the main model if their addition to the base model significantly improved fit for at least one metric of drought tolerance ($Rt$, $Rc$, or $Rs$; Tables S4,S6-S7). While we tested the significance of xylem porosity as a predictor (Table 1), we did not consider it appropriate for inclusion in the main model because of highly uneven distribution of species across categories (Table 2) and opposite drought responses of the only two diffuse-porous species (detailed below)."

* To keep the number of SI items to a reasonable number, we dropped former Fig. S6, which was not essential and not added in direct response to any reviewer comments. Keeping this figure would have required adding parallel figures for recovery and resilience, which we felt would be adding too many marginally valuable appendix figures.
...

We hope that this manuscript will now be found suitable for publication in *New Phytologist*, and we look forward to your response.

Best regards,

Kristina Anderson-Teixeira (on behalf of all authors)




\newpage

Decision: Accept subject to revision

## Referee: 1

Comments to the Author

The authors have done a thorough job of addressing my concerns and I found the revised manuscript much improved. Well done!

**Thank you.**

## Referee: 2

Comments to the Author

Thank you very much for sending me this revised version of the ms by McGregor et al. It is a very important study with a clever and appropriate sampling design, and is exceptionally well written. I enjoyed reading it again and find it very valuable. Thanks very much to the authors for tweaking the text here and there and adding detail, which made the ms even more compelling. I had a few reactions that might be useful:

72 One suggestion is that it would be better not to say that larger individuals have xylem of “greater efficiency.” Instead, Red Queen like, conduits widen allowing whole-pathlength resistance to remain constant over much of the height range of trees. Presumably selection favors variants in which leaves maintain their productivity constant insofar as is possible as an individual grows taller, and resistance as constant as possible would contribute to this. So, taller trees don’t have more efficient conduits; they widen in a way that maintains the same whole-pathlength efficiency. Here you could say something like “taller trees have wider conduits, which help maintain constant the resistance that would otherwise increase as trees grow taller.”

**We have reworded the sentence to read, "Taller trees have wider conduits in the basal portions of taller trees, both within and across species [@olson_plant_2018; @liu_hydraulic_2019] and throughout the conductive systems of angiosperms [@zach_vessel_2010; @olson_universal_2014; @olson_plant_2018], which help maintain constant the resistance that would otherwise increase as trees grow taller."**

392 “Constraint” is always such a vague term in biology (meaning everything from factors opposing selection to selection itself), with every biologist understanding something different. Replacing the term always seems to me to lead to increased clarity. Here, it could be removed entirely “previous findings that it is impossible for trees…”, I think profitably.

**We have made this change. It now reads, "Mechanistically, this is consistent with, and reinforces, previous findings that it impossible for trees to efficiently transport water to great heights and simultaneously maintain strong resistance and resilience to drought-induced embolism [@olson_plant_2018; @couvreur_water_2018; @roskilly_conflicting_2019]."**

395 if taller individuals are exposed to greater evaporative demand, then for a given photosynthetic productivity they would require greater conductance than they would need for a given height if they were sheltered. This would favor even wider conduits, making taller individuals even more vulnerable! You rightly highlight the need to separate height per se and canopy position.

**Yes, we agree. Thank you.**

With regard to root mass, this might be useful: https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1371%2Fjournal.pone.0086550&amp;data=02%7C01%7CTeixeiraK%40si.edu%7C04ca4a8deb534237b5a508d84dd84e13%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637344938706540440&amp;sdata=tiYufg0%2F%2BuRBThcGeUHuRjVDhWPmbK0xP%2Fb2moH%2F210%3D&amp;reserved=0 seem to show above-below ground biomass isometry.

**Thank you. We have added this reference in two places (intro and discussion).**

Thanks again and congratulations to the authors.

**Thank you.**

Mark Olson

## Referee: 3

Comments to the Author

This is a resubmission of a previously revised manuscript. I have enjoyed reading the manuscript. The paper is well written and the methods are clearly presented. The hypotheses are sound and well framed within the physiological implications of tree height.

The authors have satisfactorily answered most previous comments. For instance, I appreciated the discussion on the two indices Rt and Rtarima. I agree that results comparing them are pretty similar (Table S6 vs Table S7) and that authors can use Rt.

**Thank you. Because we had to cut content in order to present the recovery and resilience metrics (see below) while keeping within word limits, we have cut back on the reporting of $Rt_{ARIMA} results in the main text, but still show the full comparisons in the Appendix. Specifically, we now state in the following in the methods: "$Rt$ and $Rt_{ARIMA}$ were strongly correlated (Fig. **S5**), and showed similar responses to the independent variables of interest (cf. Tables S4-55, S8-S9). Visual review of the individual tree-ring sequences with the largest discrepancies between these metrics revealed that $Rt$ was less prone to unreasonable estimates than $Rt_{ARIMA}$. We therefore determined that use of 5-year means, as described above, were more appropriate metrics than those based on ARIMA projections." We then drop presentation of $Rt_{ARIMA}$ results in the results section.**

Yet, I still believe there are a couple of details that need revision:

1) I still think that adding the same analysis on the two other resilience indices (resilience and recovery) from Lloret et al. (2011) would increase the interest of the manuscript (as the authors acknowledge in line 476). Using DeSoto et al. 2020 as a justification is not enough. There are potential caveats in that paper and even if we accepted the general trends in growth resilience proposed in that study, studies like that of McGregor et al. apply at a different and more detailed scale, where those global relationships might not hold. This adds interest to the present ms, but for that same reason most readers will like to see a similar discussion on the other complementary growth resilience indices together in the same paper.

**Thank you for this suggestion. Although we were initially hesitant to include these other indices, we found that their addition greatly enriched the manuscript. We have added analyses parallel to those for resistance for both recovery and resilience. Because we feel that resilience is the more interesting and informative of these two, we have given it precedence for inclusion in main manuscript figures, where space is limiting. Specifically, we have added a density plot of resilience to Fig.1 (+ parallel plot for recovery in the SI), a plot of resilience by species to Fig. 3 (+ parallel plot for recovery in the SI), and plots of the best models for both recovery and resilience to Fig. 4. We have also added recovery and resilience to the hypothesis table (Table 1), and their definitions to Table 3. We have also modified the text throughout and included relevant tables presenting statistics in the supplementary info.**


2) In Line 263 it is stated that both marginal and conditional R2 are reported, but then I could only find conditional R2s in Table S6, S7. Please, report also marginal R2 in those Tables to show how much variability it is explained by the fixed effects (i.e. the traits and independent variables in Table 3). This is important so we can judge how robust the tested covariates are. I can accept what authors argue in their response (‘Tree-ring data are inherently noisy, particularly in more mesic forests. In large part, this is due to strong neighborhood effects, along with variable allocation to ring growth around the circumference of the tree. These factors contribute to the low R2, but do not negate the significance of our findings’). However, still I think that, even if (or particularly because) we see many papers today with very low variability explained (see for instance some of the analyses in the previously mentioned DeSoto et al. 2020), we should demand a minimum level of explanatory power in models in ecophysiological papers. Otherwise we cannot assure that inferences are robust enough and relationships worth to be discussed.

**We now report both marginal and conditional R2 in tables S8-S12**. 

*Maybe also add some commentary on how a lot of noise doesn't negate significant signals.*

Other comments:

- As mentioned on a previous comment, in the manuscript the authors sampled dead and live trees, but then I did not see any further mentioning to this later in the manuscript (lines 175-178 and Table 2). This would merit some discussion and further analysis, how many trees were died and how many trees were alive of those in Table 2?

*I think our argument is pretty strong, but we need to make some change to respond to this comment. Looking at resilience and recovery should help; presuming that they are high, we have a further argument that death was not caused by drought, and hence that status at coring doesn't matter.*


**We consider it extremely unlikely that the status at coring would affect drought response. We have modified the text at (former) lines 175-178 to make this more clear: "We note that drought was probably not a cause of mortality for these trees, as monthly May-Aug $PDSI$ did not drop below -1.75 in these years or the three years prior (2013-2017), and that trees cored dead displayed similar climate sensitivity to trees cored live [@helcoski_growing_2019]. Lagged drought-induced mortality would be unlikely, given that the trees analyzed here lived at least 17-18 years past the most recent major drought (1999), whereas the meta-analysis of @trugman_tree_2018 indicates that >10-year lags in drought-attributed mortality are rare."**

**We have added a footnote to Table 2 indicating where the information on numbers cored live vs dead may be found (Table S1 of Helcoski et al. 2019).**

- Figure S4 and line 333: are differences expressed by different letters correct in Figure S4? Particularly for $\pi_{tlp}$ (S4d) the boxplot suggests differences (more than, e.g. in b) among different species but then letters are similar (as discussed in line 333).

**In Figure S4, letters express signficiantly different groupings per variable. For example, the PLA values for a species in group "b" are significantly different from the PLA values for a species in group "c". However, group "b" for PLA has no bearing on group "b" for LMA, e.g., or any other variable. We have added the following context to the caption: "Letter groupings do not transfer across variables (boxplots)."**

- LMA is not shown in Figure S4, and in Table 2 there are no tests so we cannot judge whether there are differences among species for that leaf trait. Please, add also LMA to Figure S4.

**Thank you for addressing this. We have now added LMA and WD to the figure, similar to the other variables.**

- Line 135: leave turgor ‘at’ lower ….

**Thanks for catching this; fixed. Sentence now reads, "We further test predictions that species with low $PLA_{dry}$ have higher drought resistance, and that species whose leaves lose turgor at lower water potentials (more negative $\pi_{tlp}$) have higher resistance."**

- Line 272: please define dAIC. I think it should be better and more robust to stick in all cases to dAIC>2, there are only two covariates selected with <1 in Table S4.

**We now clearly define AICc at first mention, which is in the paragraph above. The sentence now reads "R-squared to assess model fit as implemented in the AICcmodavg package in R [@R-AICcmodavg]. Individual model terms were considered significant when their addition to a model improved fit at $\Delta$AICc $\ge$ 2.0, where $\Delta$AICc is the difference in AICc between models with and without the trait."**

**Although the $\Delta$AICc $\ge$ 1.0 criteria was used only for variable selection and not as a significance test, we have dropped it and now use only $\Delta$AICc $\ge$ 2.0. To account for the fact that we now consider three main response variables, we modified the criteria for inclusion of traits in the main statistical models. As now stated in the methods, "Trait variables were considered appropriate for inclusion in the main model if their addition to the base model significantly improved fit for at least one metric of drought tolerance ($Rt$, $Rc$, or $Rs$; Tables S4,S6-S7). While we tested the significance of xylem porosity as a predictor (Table 1), we did not consider it appropriate for inclusion in the main model because of highly uneven distribution of species across categories (Table 2) and opposite drought responses of the only two diffuse-porous species (detailed below)."**

- Line 312: please, refer to the corresponding Table or Supplement where this statement is supported.

**We have added this reference: "That is, drought year as a variable did not appear in any of the top models -- *i.e.*, models that were statistically indistinguishable ($\Delta$AICc<2) from the best model (see footnotes on Tables S6-S7)."** 

- Line 371-372: actually it is radial growth that is affected; whether that can be extrapolated to the tree level is something that needs to be demonstrated.

**This is true. Of course, tree biomass growth is almost always inferred from radial or diameter growth, sometimes in conjunction with height, using allometries. The issue of whether radial stem growth (or BAI, as examined here) actually translates directly to biomass growth goes far beyond the present study. To make sure this is clearly defined here, we've specified that we're considering stem growth in a couple key places:**

* **in the introduction, where we define resistance: "Here, we examine how tree height, microenvironment characteristics, and species' traits collectively shape drought resistance, defined as the ratio of annual stem growth in a drought year to that which would be expected in the absence of drought based on previous years' growth."**

* **in the sentence identified above: "These findings advance our knowledge of the factors that make trees vulnerable to stem growth declines during drought and, by extension, likely make them more vulnerable to mortality [@sapes_plant_2019]."**

Line 385 vs lines 308-309 and line 338: does that mean that there was a correlation between canopy position and positive Rt? Can it also be related to moisture sensitivity of different species, or to niche (microenvironment) partitioning among species? (as nicely discussed in lines 420-422). I see from lines 445-450 that sampled FAGR were small, which is coherent with the authors’ statement.

**Yes, although we do not include canopy position in our statistical models. To make the link between high $Rt$ and increased growth, we have modified the sentence previously on line 385 to read, "Across all three droughts, the majority of trees experienced reduced growth, but a substantial portion (e.g., short understory trees, species with drought resistant traits; Fig. **4**) had increased growth (Fig. **1b**), consistent with prior observations that smaller trees can exhibit increased growth rates during drought [@bennett_larger_2015]."**

*(for reference, to be deleted:)*

*385: Across all three droughts, the majority of trees experienced reduced growth, but a substantial portion had increased growth (Fig. 1b),*

*208-309: However, some individuals exhibited increased growth, i.e., Rt > 1.0: 26% of trees in 1966, 22% in 1977, and 26% in 1999.*

*338: Averaged across all droughts, Rt was lowest in Liriodendron tulipifera (mean Rt = 0.66) and highest in Fagus grandifolia (mean Rt = 0.99).*

Table S5: no need to specify dAIC>1.

**This is fixed.**

## Citations
